
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback keeps `prisma generate` working in CI without a real DB connection
    url: process.env.DATABASE_URL ?? "mongodb://localhost:27017/prepai",
  },
});
